spring:
  application:
    name: weather-service
  boot:
    admin:
      client:
        instance:
          api-gateway-port: 17957
          management-base-url: http://localhost:${spring.boot.admin.client.instance.api-gateway-port}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

appid: 22f87a17fb25f8b77a8c442aac59ec09


url:
  external-api:
    weather: https://api.openweathermap.org/data/2.5/weather

server:
  port: 0